name: Build and release jar
on:
    push:
        tags:
            - "*"

jobs:
    build-and-release:
        runs-on: ubuntu-latest
        container: openjdk:16
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Build jar
            - run: ./gradlew remapJar
            - name: Publish release
              uses: softprops/action-gh-release@v1
              with:
                  name: ${{ github.ref }}
                  files: build/libs/*[^-dev].jar
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
